### ISSUE TITLE
Team Webhook XMl Issue

### ISSUE THREAD

**Issue by vginjupalli** [oneboredcoder/zabbix-teams-webhook#1]
Details Media type test failed.
SyntaxError: invalid json (at offset 1)
at [anon] (duktape.c:34342) internal
at parse () native strict preventsyield
at [anon] (function:142) preventsyield

I am getting the following error when i try to test it. Any idea what's going on

**Comment by vginjupalli** [comment]
![image](https://user-images.githubusercontent.com/31081335/80154368-a510c500-857c-11ea-9ee5-57796bebc2aa.png)

**Comment by oneboredcoder** [comment]
While testing, at least eventValue is required. Try with 0 or 1
