### ISSUE TITLE
Unable to import template on zabbix 4.4.3

### ISSUE THREAD

**Issue by scoopex** [oneboredcoder/zabbix-teams-webhook#2]
I was not able to import the template, because it seems that a xml field is missing.
(see screenshot)

![grafik](https://user-images.githubusercontent.com/288876/82381298-3ebb7d00-9a2a-11ea-8595-40ab01608639.png)

**Comment by oneboredcoder** [comment]
You implemented this field improperly in your fork.
1. put it inside `<parameters></parameters>` tags.
2. it's supposed to be like this:
`<parameter><name>show_event_menu</name><value>NO</value></parameter>`

**Comment by oneboredcoder** [comment]
If `<show_event_menu>` is set in xml you need to add two more fields `<event_menu_url>` and `<event_menu_name>`. If show_event_menu is set to NO (like in your fork), both of those fields must be empty.
However if you don't need event menu, `<show_event_menu>` tag is not required in xml.
